One hot vector or nominal encoding

In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [ ]:
## create a simple dataframe

df = pd.DataFrame({
    'color': ['red', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1  green
2  green
3    red
4   blue

In [5]:
##create an instance of Onehotencoder
encoder=OneHotEncoder()

In [8]:
##perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [10]:
import pandas as pd 
encoder_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [ ]:
##for new data
encoder.transform([['blue']]).toarray()

Label Encoding

In [10]:
df.head()

   color
0    red
1  green
2  green
3    red
4   blue

In [11]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [14]:
lbl_encoder.fit_transform(df['color'])

array([2, 1, 1, 2, 0])

In [15]:
lbl_encoder.transform([['red']])

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [16]:
lbl_encoder.transform([['blue']])

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [17]:
lbl_encoder.transform([['green']])

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

Ordinal Encoding

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [19]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [20]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [21]:
##create an instance of OrdinalEncoder and then transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [22]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [23]:
encoder.transform([['small']])

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

Target guided ordinal encoding

In [5]:
import pandas as pd

df = pd.DataFrame({
    'city' : ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [6]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [11]:
mean_price = df.groupby('city')['price'].mean();

In [12]:
mean_price

city
London      150.0
New York    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [13]:
df['city_encoded'] = df['city'].map(mean_price)

In [15]:
df[['price','city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0